name: test-terraform-code

on:
  push:
    branches:
      - 'main'
      - 'releases/**'
      - 'feature/**'
      
jobs:

  test-tf-code:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
          
      - name: Test infrastructure FMC/AWS
        uses: bridgecrewio/checkov-action@master
        with:
          directory: FMC/AWS/Standalone
          framework: terraform
          
      - name: Test infrastructure FMC/GSP
        if: always()
        uses: bridgecrewio/checkov-action@master
        with:
          directory: FMC/GCP/Terraform
          framework: terraform
          
      - name: Test infrastructure FMC/Azure
        if: always()
        uses: bridgecrewio/checkov-action@master
        with:
          directory: FMC/Azure/Terraform/standalone
          framework: terraform 
