name: test-terraform-code

on:
  push:
    branches: [ main ]

jobs:

  test:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Test with Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: ASA/AWS/Terraform/ASA_A_A_Multiple_AZ
          framework: terraform 
